# Bot
# ---


Token:  # the bot token. Can be found on discord.com/developers
""

Prefix: # the default prefix for invoking a command with the bot
","

Color:  # the main color used by the bot
0xfa2a3f


# Website
# -------

# coming soon